enableColors: true

enableTelemetry: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpFallbackMode: all

pnpMode: loose

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-2.4.2.cjs
